name: main

on:
  push:
    branches: ["main"]

jobs:
  wheel_build_full:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    - name:  build wheels
      uses: pypa/cibuildwheel@v2.12.1
      env:
        SPLINEPY_GITHUB_ACTIONS_BUILD: True

    - uses: actions/upload-artifact@v3
      with:
        path: ./wheelhouse/*.whl

  upload_test_pypi:
    needs: [wheel_build_full]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: artifact
          path: dist

      - uses: pypa/gh-action-pypi-publish@v1.6.1
        with:
          skip_existing: true
          user: __token__
          password: ${{ secrets.PYPI_TOKEN }}
