name: main

on:
  push:
    branches: ["main"]

jobs:
  macos_wheel:
    runs-on: macos-latest
    strategy:
      matrix:
        arch: [x86_64, arm64]
        cw_build: ["cp36-*", "cp37-*", "cp38-*", "cp39-*", "cp310-*", "cp311-*"]

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    - name: build wheels
      uses: pypa/cibuildwheel@v2.13.1
      env:
        CIBW_ARCHS: ${{ matrix.arch }}
        CIBW_BUILD: ${{ matrix.cw_build }}
        CIBW_TEST_SKIP: "*-macosx_arm64"
        SPLINEPY_GITHUB_ACTIONS_BUILD: True

    - uses: actions/upload-artifact@v3
      with:
        path: ./wheelhouse/*.whl
        retention-days: 2

  linux_wheel:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [x86_64]
        cw_build: ["cp36*many*", "cp37*many*", "cp38*many*", "cp39*many*", "cp310*many*", "cp311*many*"]

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    - name: build wheels
      uses: pypa/cibuildwheel@v2.13.1
      env:
        CIBW_ARCHS: ${{ matrix.arch }}
        CIBW_BUILD: ${{ matrix.cw_build }}
        SPLINEPY_GITHUB_ACTIONS_BUILD: True

    - uses: actions/upload-artifact@v3
      with:
        path: ./wheelhouse/*.whl
        retention-days: 2

  windows_wheel:
    runs-on: windows-latest
    strategy:
      matrix:
        arch: [x86, AMD64, ARM64]
        cw_build: ["cp36-*", "cp37-*", "cp38-*", "cp39-*", "cp310-*", "cp311-*"]

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    - name: build wheels
      uses: pypa/cibuildwheel@v2.13.1
      env:
        CIBW_ARCHS: ${{ matrix.arch }}
        CIBW_BUILD: ${{ matrix.cw_build }}
        CIBW_TEST_SKIP: "*-win_arm64"
        SPLINEPY_GITHUB_ACTIONS_BUILD: True

    - uses: actions/upload-artifact@v3
      with:
        path: ./wheelhouse/*.whl
        retention-days: 2

  source_dist:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Build sdist
      run: pipx run build --sdist

    - uses: actions/upload-artifact@v3
      with:
        path: ./dist/*
        retention-days: 2


  upload_test_pypi:
    needs: [wheel_build_full, source_dist]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: artifact
          path: dist

      - uses: pypa/gh-action-pypi-publish@v1.6.1
        with:
          skip_existing: true
          user: __token__
          password: ${{ secrets.PYPI_TOKEN }}
