name: Builds minimal and runs tests

on:
  push

permissions:
  contents: read

jobs:
  build_and_tests:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: [3.9]
        os: [ubuntu-latest, macos-latest]

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    - name: Set up  ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
        
    - name: install dependencies
      run: pip install numpy pytest
            
    - name: build splinepy linux - clang12, test
      if: matrix.os == 'ubuntu-latest'
      run: |
        CC=clang-12 CXX=clang++-12 python3 setup.py install --minimal
        pytest tests

    - name: build splinepy linux - gcc10, test
      if: matrix.os == 'ubuntu-latest'
      run: |
        CC=gcc-10 CXX=g++-10 python3 setup.py install --minimal
        pytest tests

    - name: build splinepy macos, test
      if: matrix.os == 'macos-latest'
      run: |
        python3 setup.py install --minimal
        pytest tests
